// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example // import "github.com/johanbrandhorst/grpc-auth-example/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Role int32

const (
	Role_GUEST  Role = 0
	Role_MEMBER Role = 1
	Role_ADMIN  Role = 2
)

var Role_name = map[int32]string{
	0: "GUEST",
	1: "MEMBER",
	2: "ADMIN",
}
var Role_value = map[string]int32{
	"GUEST":  0,
	"MEMBER": 1,
	"ADMIN":  2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}
func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_example_c040f6aaec094c10, []int{0}
}

type User struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Role                 Role                 `protobuf:"varint,2,opt,name=role,enum=example.Role" json:"role,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_date,json=createDate" json:"create_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_c040f6aaec094c10, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_GUEST
}

func (m *User) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

type UserRole struct {
	Role                 Role     `protobuf:"varint,1,opt,name=role,enum=example.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_c040f6aaec094c10, []int{1}
}
func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (dst *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(dst, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_GUEST
}

type DeleteUserRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_c040f6aaec094c10, []int{2}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "example.User")
	proto.RegisterType((*UserRole)(nil), "example.UserRole")
	proto.RegisterType((*DeleteUserRequest)(nil), "example.DeleteUserRequest")
	proto.RegisterEnum("example.Role", Role_name, Role_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error)
	ListUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UserService_ListUsersClient, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/example.UserService/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UserService_ListUsersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UserService_serviceDesc.Streams[0], c.cc, "/example.UserService/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ListUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceListUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceListUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/example.UserService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	AddUser(context.Context, *User) (*empty.Empty, error)
	ListUsers(*empty.Empty, UserService_ListUsersServer) error
	DeleteUser(context.Context, *DeleteUserRequest) (*empty.Empty, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ListUsers(m, &userServiceListUsersServer{stream})
}

type UserService_ListUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceListUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceListUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserService_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_c040f6aaec094c10) }

var fileDescriptor_example_c040f6aaec094c10 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0xdd, 0x8a, 0x20, 0x43, 0x20, 0xb8, 0x07, 0x43, 0xea, 0x41, 0xc4, 0x4b, 0x63, 0x42,
	0x4b, 0xd0, 0x93, 0x78, 0x10, 0x42, 0x63, 0x4c, 0xc4, 0x43, 0x81, 0x8b, 0x17, 0xb3, 0x6d, 0xc7,
	0xb6, 0xa6, 0x65, 0xeb, 0x76, 0x4b, 0xf4, 0x93, 0xf9, 0xf5, 0x4c, 0x5b, 0xfe, 0x44, 0x08, 0xc7,
	0x37, 0xf3, 0xfa, 0x7e, 0x7d, 0xb3, 0x50, 0xc7, 0x6f, 0x16, 0xc5, 0x21, 0xea, 0xb1, 0xe0, 0x92,
	0xd3, 0xca, 0x4a, 0xaa, 0x17, 0x1e, 0xe7, 0x5e, 0x88, 0x46, 0x3e, 0xb6, 0xd3, 0x0f, 0x03, 0xa3,
	0x58, 0xfe, 0x14, 0x2e, 0xf5, 0x72, 0x77, 0x29, 0x83, 0x08, 0x13, 0xc9, 0xa2, 0xb8, 0x30, 0x74,
	0x96, 0x50, 0x9a, 0x27, 0x28, 0x68, 0x03, 0x94, 0xc0, 0x6d, 0x91, 0x36, 0xd1, 0xea, 0x96, 0x12,
	0xb8, 0xf4, 0x0a, 0x4a, 0x82, 0x87, 0xd8, 0x52, 0xda, 0x44, 0x6b, 0xf4, 0xeb, 0xfa, 0x1a, 0x6e,
	0xf1, 0x10, 0xad, 0x7c, 0x45, 0x07, 0x50, 0x73, 0x04, 0x32, 0x89, 0xef, 0x2e, 0x93, 0xd8, 0x3a,
	0x6e, 0x13, 0xad, 0xd6, 0x57, 0xf5, 0x82, 0xa8, 0xaf, 0x89, 0xfa, 0x6c, 0x4d, 0xb4, 0xa0, 0xb0,
	0x8f, 0x99, 0xc4, 0x4e, 0x17, 0x4e, 0x33, 0x6e, 0x16, 0xb7, 0x61, 0x91, 0x83, 0xac, 0xce, 0x35,
	0x9c, 0x8d, 0x31, 0x44, 0x89, 0xf9, 0x47, 0xf8, 0x95, 0x62, 0x22, 0x77, 0xff, 0xf9, 0x46, 0x83,
	0x52, 0x9e, 0x57, 0x85, 0x93, 0xa7, 0xb9, 0x39, 0x9d, 0x35, 0x8f, 0x28, 0x40, 0x79, 0x62, 0x4e,
	0x46, 0xa6, 0xd5, 0x24, 0xd9, 0x78, 0x38, 0x9e, 0x3c, 0xbf, 0x36, 0x95, 0xfe, 0x2f, 0x81, 0x5a,
	0x96, 0x34, 0x45, 0xb1, 0x0c, 0x1c, 0xa4, 0x3d, 0xa8, 0x0c, 0x5d, 0x37, 0x3f, 0xc4, 0x16, 0x9f,
	0x49, 0xf5, 0x7c, 0xaf, 0x8f, 0x99, 0x9d, 0x97, 0xde, 0x41, 0xf5, 0x25, 0x48, 0x64, 0xe6, 0x49,
	0xe8, 0x01, 0x93, 0xfa, 0x3f, 0xab, 0x47, 0xe8, 0x23, 0xc0, 0xb6, 0x06, 0x55, 0x37, 0xeb, 0xbd,
	0x6e, 0x87, 0xb8, 0xa3, 0x87, 0xb7, 0x7b, 0x2f, 0x90, 0x7e, 0x6a, 0xeb, 0x0e, 0x8f, 0x8c, 0x4f,
	0xee, 0xb3, 0x85, 0x2d, 0xd8, 0xc2, 0xf5, 0xb9, 0x48, 0xa4, 0xe1, 0x89, 0xd8, 0xe9, 0xb2, 0x54,
	0xfa, 0xdd, 0x55, 0x72, 0xf1, 0xf0, 0x83, 0x95, 0xb2, 0xcb, 0xb9, 0xbc, 0xfd, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x93, 0x19, 0x0b, 0xa5, 0x4c, 0x02, 0x00, 0x00,
}
